name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Update this to match your project's Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # If you use requirements.txt to manage dependencies, uncomment the next line:
        # pip install -r requirements.txt

    - name: Run pylint on all Python files
      run: |
        # This will recursively lint all .py files in the repo
        pylint $(git ls-files '*.py')
